version: 2
updates:
  # Maven依赖更新
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    # 限制同时开放的PR数量
    open-pull-requests-limit: 5
    # 目标分支设置为dev，避免直接合并到main
    target-branch: "dev"
    reviewers:
      - "AkkoSpace"
    assignees:
      - "AkkoSpace"
    # 使用gitmoji编码格式
    commit-message:
      prefix: ":arrow_up:"
      prefix-development: ":arrow_up:"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
      - "auto-dependency-update"
    # 更严格的忽略规则
    ignore:
      # 忽略主要版本更新，需要手动处理
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.postgresql:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.openjdk:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "*:sonar-maven-plugin"
        update-types: ["version-update:semver-major"]

  # Docker依赖更新
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    # Docker更新也目标到dev分支
    target-branch: "dev"
    reviewers:
      - "AkkoSpace"
    assignees:
      - "AkkoSpace"
    commit-message:
      prefix: ":arrow_up:"
      prefix-development: ":arrow_up:"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "auto-dependency-update"

  # GitHub Actions依赖更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "11:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    # GitHub Actions更新也目标到dev分支
    target-branch: "dev"
    reviewers:
      - "AkkoSpace"
    assignees:
      - "AkkoSpace"
    commit-message:
      prefix: ":arrow_up:"
      prefix-development: ":arrow_up:"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-dependency-update"
