# 服务器配置
server:
  port: ${SERVER_PORT:26300}

spring:
  application:
    name: backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/codeas?currentSchema=platform_schema&searchpath=platform_schema,foundation_schema
    username: ${DB_USERNAME:codeas}
    password: ${DB_PASSWORD:codeas123}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: BackendHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: false
      key-prefix: "backend:cache:"
      use-key-prefix: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration
    schemas: foundation_schema,platform_schema,business_schema,integration_schema
    default-schema: platform_schema

  # Spring Security 基础配置
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    default-schema: platform_schema
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted
      logic-delete-value: true
      logic-not-delete-value: false
      update-strategy: not_null
      insert-strategy: not_null
      select-strategy: not_empty
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: space.akko.platform.*.model.entity

# 平台配置
platform:
  security:
    jwt:
      secret: ${JWT_SECRET:YWtrby1iYWNrZW5kLXBsYXRmb3JtLXNlY3JldC1rZXktMjAyNA==}
      expiration: 86400 # 24小时
      refresh-expiration: 604800 # 7天
      header: Authorization
      prefix: "Bearer "

    password:
      encoder: bcrypt
      strength: 10

    login:
      max-attempts: 5
      lock-duration: 900 # 15分钟

  cache:
    l1:
      enabled: true
      maximum-size: 1000
      expire-after-write: 5m
    l2:
      enabled: true
      default-ttl: 30m

  audit:
    enabled: true
    async: true
    include-request-body: false
    include-response-body: false
    log:
      retention-days: 90

  file:
    upload:
      path: ./uploads
      max-size: 10485760  # 10MB
      allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt

  config:
    hot-reload: true

  api-docs:
    export:
      enabled: true
      output-dir: ./docs/api/generated
      formats: json,yaml
      include-timestamp: true

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OpenAPI文档配置
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  info:
    title: CodeAS Backend API
    description: CodeAS 平台后端接口文档
    version: 0.0.1
    contact:
      name: akko
      email: akko@akko.space

# 日志配置
logging:
  level:
    root: WARN
    space.akko: INFO
    org.springframework.security: WARN
    org.springframework.cache: WARN
    com.baomidou.mybatisplus: WARN
    org.springframework.web: WARN
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/backend.log
    max-size: 100MB
    max-history: 30
